apiVersion: v1
kind: Service
metadata:
  name: diaspomoney-dev-service
  namespace: diaspomoney
spec:
  selector:
    app: diaspomoney-dev
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
