apiVersion: v1
kind: Secret
metadata:
  name: mongo-express-secrets
  namespace: diaspomoney-prod
  labels:
    app: diaspomoney
    component: mongo-express
type: Opaque
stringData:
  username: "admin"
  password: "CHANGE_ME_MONGO_EXPRESS_PASSWORD"

