apiVersion: v1
kind: Service
metadata:
  name: diaspomoney-redis
  namespace: diaspomoney
  labels:
    app: diaspomoney-redis
spec:
  selector:
    app: diaspomoney-redis
  ports:
  - port: 6379
    targetPort: 6379
    protocol: TCP
    name: redis
  type: ClusterIP

