apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: mongo-express-ingressroute-https
  namespace: diaspomoney
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`mongo.diaspomoney.fr`)
      kind: Rule
      services:
        - name: mongo-express
          port: 8081
  tls:
    certResolver: le
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: mongo-express-ingressroute-http
  namespace: diaspomoney
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`mongo.diaspomoney.fr`)
      kind: Rule
      middlewares:
        - name: https-redirect
      services:
        - name: mongo-express
          port: 8081

