apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: mongo-express-ingressroute
  namespace: diaspomoney
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`mongo.diaspomoney.fr`)
      kind: Rule
      services:
        - name: mongo-express
          port: 8081
  tls:
    certResolver: le

