apiVersion: v1
kind: ConfigMap
metadata:
  name: diaspomoney-config
  namespace: diaspomoney-prod
  labels:
    app: diaspomoney
data:
  # Application Configuration
  NODE_ENV: "production"
  PORT: "3000"
  HOSTNAME: "0.0.0.0"
  NEXT_TELEMETRY_DISABLED: "1"
  
  # MongoDB Configuration
  MONGODB_URI: "mongodb://mongodb:27017/diaspomoney"
  MONGODB_DATABASE: "diaspomoney"
  
  # Redis Configuration
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  
  # API URLs (Ã  personnaliser selon votre environnement)
  NEXT_PUBLIC_API_URL: "https://app.diaspomoney.fr"
  AUTH_URL: "https://app.diaspomoney.fr"
  NEXTAUTH_URL: "https://app.diaspomoney.fr"
  
  # Application URLs
  APP_URL: "https://app.diaspomoney.fr"
  BASE_URL: "https://app.diaspomoney.fr"
