apiVersion: v1
kind: ServiceAccount
metadata:
  name: diaspomoney-sa
  namespace: diaspomoney-prod
  labels:
    app: diaspomoney

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: diaspomoney-prod
  name: diaspomoney-role
  labels:
    app: diaspomoney
rules:
- apiGroups: [""]
  resources: ["pods", "services", "endpoints", "configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: diaspomoney-rolebinding
  namespace: diaspomoney-prod
  labels:
    app: diaspomoney
subjects:
- kind: ServiceAccount
  name: diaspomoney-sa
  namespace: diaspomoney-prod
roleRef:
  kind: Role
  name: diaspomoney-role
  apiGroup: rbac.authorization.k8s.io

